/**
 * Read-only contracts for catalog PowerShell actions.
 *
 * These are deliberately kept outside the JSON catalog so a future catalog
 * refresh cannot silently make an arbitrary script eligible for Tune Now.
 * Only IDs listed here receive a verifier; every other PowerShell action stays
 * explicit-only and reports unknown rather than pretending it stuck.
 */

// Network verifiers must resolve the same physical adapter that carries the
// active IPv4 default route. Checking every adapter can report a false pass
// when a VPN, Hyper-V switch, or stale disconnected NIC is the one that was
// actually changed.
const ACTIVE_PHYSICAL_ROUTE =
  "$ErrorActionPreference='Stop'; $route=@(Get-NetRoute -DestinationPrefix '0.0.0.0/0' -AddressFamily IPv4 | Where-Object { $_.NextHop -and $_.NextHop -ne '0.0.0.0' -and $_.InterfaceIndex } | Sort-Object @{Expression='RouteMetric';Ascending=$true},@{Expression='InterfaceMetric';Ascending=$true} | Select-Object -First 1); if($route.Count -ne 1){Write-Output 'Active IPv4 route unavailable; verification is unknown.'; exit 2}; $a=Get-NetAdapter -Physical -InterfaceIndex ([int]$route[0].InterfaceIndex) | Select-Object -First 1; if(-not $a){Write-Output 'Active route is not a physical adapter; verification is unknown.'; exit 2}; $idx=[int]$a.ifIndex; $guid=''; if($a.PSObject.Properties.Name -contains 'InterfaceGuid'){$guid=[string]$a.InterfaceGuid}; $pnp=''; if($a.PSObject.Properties.Name -contains 'PnpDeviceID'){$pnp=[string]$a.PnpDeviceID}; $identity=$pnp; if([string]::IsNullOrWhiteSpace($identity)){$identity=$guid}; if([string]::IsNullOrWhiteSpace($identity)){$identity=[string]$a.Name};"

// `powercfg /query` accepts a scheme and an optional subgroup, not a setting
// GUID as a third positional argument. Query the subgroup once, then isolate
// the requested setting block so another setting's AC/DC value cannot produce
// a false pass. Unsupported/hidden settings are a capability result, not an
// ambiguous failure that should roll back the rest of Asta.
const powerSettingVerifier = (subgroupGuid: string, settingGuid: string, label: string): string =>
  `$q=@(powercfg /query SCHEME_CURRENT ${subgroupGuid} 2>&1) -join [Environment]::NewLine; $exit=$LASTEXITCODE; if($exit -ne 0 -or [string]::IsNullOrWhiteSpace($q)){if($q -match '(?i)invalid parameters|not found|does not exist|unable to find'){Write-Output 'NOT_APPLICABLE: ${label} is not exposed by the active power plan.'; exit 2}; Write-Output 'UNKNOWN: Windows did not return the ${label} power setting.'; exit 2}; $block=[regex]::Match($q,'(?is)Power Setting GUID:\\s*${settingGuid}.*?(?=Power Setting GUID:|$)').Value; if([string]::IsNullOrWhiteSpace($block)){Write-Output 'NOT_APPLICABLE: ${label} is not exposed by the active power plan.'; exit 2}; $ac=[regex]::Match($block,'(?i)Current AC Power Setting Index:\\s+0x([0-9a-f]+)').Groups[1].Value; $dc=[regex]::Match($block,'(?i)Current DC Power Setting Index:\\s+0x([0-9a-f]+)').Groups[1].Value; if([string]::IsNullOrWhiteSpace($ac) -or [string]::IsNullOrWhiteSpace($dc)){Write-Output 'UNKNOWN: Windows returned the ${label} block without readable AC/DC values.'; exit 2}; if($ac -eq '00000000' -and $dc -eq '00000000'){exit 0}; Write-Output ('MISMATCH: ${label} is not disabled for both AC and DC (AC 0x'+$ac+', DC 0x'+$dc+').'); exit 1`

const PCI_EXPRESS_SUBGROUP = '501a4d13-42af-4429-9fd1-a8218c268e20'
const PCI_EXPRESS_LINK_STATE = 'ee12f906-d277-404b-b6da-e5fa1a576df5'
const USB_SUBGROUP = '2a737441-1930-4402-8d77-b2bebba308a3'
const USB_LINK_POWER = 'd4e23884-9b93-478a-9e23-77356611f124'

export const POWERSHELL_VERIFIERS: Record<string, string> = {
  'network.tcp.ack-nodelay':
    "$ErrorActionPreference='Stop'; $root='HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces'; $paths=@(Get-ChildItem -LiteralPath $root -ErrorAction Stop | ForEach-Object { $p=Get-ItemProperty -LiteralPath $_.PSPath -ErrorAction SilentlyContinue; $ips=@($p.IPAddress)+@($p.DhcpIPAddress); if(@($ips | Where-Object { $_ -and $_ -ne '0.0.0.0' -and $_ -ne '::' -and $_ -ne '127.0.0.1' -and $_ -ne '::1' }).Count -gt 0){ $_.PSPath } }); if($paths.Count -eq 0){Write-Output 'UNKNOWN: No IP-bound TCP/IP interface profile was found; Windows did not expose a safe target.'; exit 2}; $bad=@($paths | Where-Object { $p=Get-ItemProperty -LiteralPath $_ -ErrorAction Stop; [int]$p.TcpAckFrequency -ne 1 -or [int]$p.TCPNoDelay -ne 1 }); if($bad.Count -gt 0){Write-Output ('MISMATCH: TCP immediate-ACK/Nagle target is missing on '+$bad.Count+' IP-bound interface profile(s).'); exit 1}; exit 0",
  'network.qos.dscp-tag':
    "$ErrorActionPreference='Stop'; $path='FortniteClient-Win64-Shipping.exe'; $localRules=@(Get-NetQosPolicy -PolicyStore localhost -ErrorAction Stop); $activeRules=@(Get-NetQosPolicy -PolicyStore ActiveStore -ErrorAction Stop); $localFortnite=@($localRules | Where-Object { (($_.AppPathNameMatchCondition).Trim([char]34)) -like ('*' + $path) }); $activeFortnite=@($activeRules | Where-Object { (($_.AppPathNameMatchCondition).Trim([char]34)) -like ('*' + $path) }); if($activeFortnite.Count -eq 0){if($localFortnite.Count -eq 0){Write-Output 'MISMATCH: No Fortnite QoS policy is stored locally or effective in ActiveStore.'; exit 1}; $found=($localFortnite | ForEach-Object { \"$($_.Name): DSCP $($_.DSCPAction), Owner=$($_.Owner)\" }) -join '; '; Write-Output \"UNKNOWN: Fortnite QoS is stored locally but not present in ActiveStore, so Windows does not report it as effective. Found: $found. Review the policy source/profile before retrying.\"; exit 2}; $conflicts=@($activeFortnite | Where-Object { [int]$_.DSCPAction -ne 46 }); $found=($activeFortnite | ForEach-Object { \"$($_.Name): AppPath=$($_.AppPathNameMatchCondition), DSCP=$($_.DSCPAction), Owner=$($_.Owner)\" }) -join '; '; if($conflicts.Count -gt 0){Write-Output \"MISMATCH: Effective Fortnite QoS policy action is not DSCP 46. Found: $found\"; exit 1}; Write-Output \"Verified effective Fortnite QoS target (DSCP 46): $found\"",
  'ps.mmagent.disable-mc':
    "$ErrorActionPreference='Stop'; $m=Get-MMAgent -ErrorAction Stop; if($null -eq $m.MemoryCompression){Write-Output 'UNKNOWN: Windows did not expose the MemoryCompression state.'; exit 2}; if(-not [bool]$m.MemoryCompression){exit 0}; Write-Output 'MISMATCH: Memory Compression is still enabled.'; exit 1",
  'ps.mmagent.disable-pagecombining':
    "$ErrorActionPreference='Stop'; $m=Get-MMAgent -ErrorAction Stop; if($null -eq $m.PageCombining){Write-Output 'UNKNOWN: Windows did not expose the PageCombining state.'; exit 2}; if(-not [bool]$m.PageCombining){exit 0}; Write-Output 'MISMATCH: Page Combining is still enabled.'; exit 1",
  'ps.power.dt-tournament':
    "$ErrorActionPreference='Stop'; $statePath=Join-Path $env:LOCALAPPDATA 'optmaxxing\\backups\\siege-power-plan.json'; $planName='Optimizationmaxxing Ultimate Performance'; $legacyPlanName='Optimizationmaxxing Siege'; $active=powercfg /getactivescheme | Out-String; $activeGuid=[regex]::Match($active,'[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}').Value; if(-not $activeGuid){Write-Output 'UNKNOWN: Active power plan could not be read; run the installed app as Administrator and retry.'; exit 2}; if(-not (Test-Path -LiteralPath $statePath)){ $plans=@(powercfg /list); $ownedPlan=@($plans | Where-Object {$_ -match ('\\('+[regex]::Escape($planName)+'\\)') -or $_ -match ('\\('+[regex]::Escape($legacyPlanName)+'\\)')}); if($ownedPlan.Count -gt 0){Write-Output 'UNKNOWN: An app-owned Ultimate Performance plan exists but its recovery record is missing; use Settings -> Restore/repair before retrying.'; exit 2}; Write-Output 'NOT_CONFIGURED: No app-owned Ultimate Performance plan or recovery record exists; first apply will create both before activation.'; exit 2}; try{$state=Get-Content -LiteralPath $statePath -Raw | ConvertFrom-Json}catch{Write-Output 'UNKNOWN: Power-plan recovery data cannot be read; use Settings -> Restore/repair before retrying.'; exit 2}; $schema=[int]$state.schema; $pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'; if($schema -notin @(1,2) -or $state.owner -ne 'optimizationmaxxing' -or $state.created -ne $true -or [string]$state.originalGuid -notmatch $pattern -or [string]$state.targetGuid -notmatch $pattern -or [string]$state.originalGuid -eq [string]$state.targetGuid){Write-Output 'UNKNOWN: Power-plan ownership record is invalid; use Settings -> Restore/repair before retrying.'; exit 2}; if($schema -eq 1){$planName=$legacyPlanName}elseif([string]$state.planName -ne $planName){Write-Output 'UNKNOWN: Power-plan name is invalid; use Settings -> Restore/repair before retrying.'; exit 2}; $target=[string]$state.targetGuid; $line=@(powercfg /list | Where-Object {$_ -match [regex]::Escape($target)}); if($line.Count -ne 1 -or $line[0] -notmatch ('\\('+[regex]::Escape($planName)+'\\)')){Write-Output 'UNKNOWN: Owned Ultimate Performance plan is missing or was renamed; use Settings -> Restore/repair before retrying.'; exit 2}; if($activeGuid -ne $target){Write-Output 'MISMATCH: Active power-plan GUID differs from the owned Ultimate Performance plan.'; exit 1}; exit 0",
  'process.wake-timers.disable':
    "$q=powercfg /query SCHEME_CURRENT SUB_SLEEP BD3B718A-0680-4D9D-8AB2-E1D2B4AC806D | Out-String; if($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($q)){Write-Output 'UNKNOWN: Windows did not return the wake-timer power setting.'; exit 2}; if($q -match '0x00000000'){exit 0}; Write-Output 'MISMATCH: Wake timers are not disabled in the active power plan.'; exit 1",
  'net.nic.interrupt-moderation.disable':
    `${ACTIVE_PHYSICAL_ROUTE}$p=Get-NetAdapterAdvancedProperty -Name $a.Name -DisplayName 'Interrupt Moderation' -ErrorAction SilentlyContinue; if(-not $p){Write-Output 'NOT_APPLICABLE: Interrupt Moderation is not exposed by the active adapter.'; exit 2}; if($p.DisplayValue -notmatch '^(Disabled|Off|No)$'){Write-Output ('MISMATCH: Interrupt Moderation is '+$p.DisplayValue+' on the active adapter; target is Disabled.'); exit 1}; exit 0`,
  'net.nic.flow-control.disable':
    `${ACTIVE_PHYSICAL_ROUTE}$p=Get-NetAdapterAdvancedProperty -Name $a.Name -DisplayName 'Flow Control' -ErrorAction SilentlyContinue; if(-not $p){Write-Output 'NOT_APPLICABLE: Flow Control is not exposed by the active adapter.'; exit 2}; if($p.DisplayValue -notmatch '^(Disabled|Off|No)$'){Write-Output ('MISMATCH: Flow Control is '+$p.DisplayValue+' on the active adapter; target is Disabled.'); exit 1}; exit 0`,
  'net.nic.rss.enable':
    `${ACTIVE_PHYSICAL_ROUTE}$f=Join-Path $env:LOCALAPPDATA 'optmaxxing\\backups\\nic-rss-stash.json'; $r=Get-NetAdapterRss -Name $a.Name -ErrorAction SilentlyContinue; if(-not $r){Write-Output 'NOT_APPLICABLE: RSS is not exposed by the active adapter.'; exit 2}; if(-not (Test-Path -LiteralPath $f)){Write-Output 'NOT_CONFIGURED: RSS recovery record is absent; first apply will save the current RSS state for this adapter before enabling it.'; exit 2}; try{$state=Get-Content -LiteralPath $f -Raw | ConvertFrom-Json}catch{Write-Output 'UNKNOWN: RSS ownership record cannot be read; use Settings -> Restore/repair before retrying.'; exit 2}; if([int]$state.schema -ne 2 -or [string]$state.owner -ne 'optimizationmaxxing' -or [string]$state.identity -ne $identity -or [int]$state.interfaceIndex -ne $idx){Write-Output 'UNKNOWN: RSS ownership record does not match the active adapter; refusing to guess which device to restore.'; exit 2}; if(-not [bool]$r.Enabled){Write-Output 'MISMATCH: RSS is not enabled on the active adapter.'; exit 1}; exit 0`,
  'process.core-parking.disable':
    "$q=powercfg /query SCHEME_CURRENT SUB_PROCESSOR 0cc5b647-c1df-4637-891a-dec35c318583 | Out-String; if($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($q)){Write-Output 'UNKNOWN: Windows did not return the core-parking power setting.'; exit 2}; if([regex]::Matches($q,'0x00000064').Count -ge 2){exit 0}; Write-Output 'MISMATCH: Core parking is not disabled for both AC and DC.'; exit 1",
  'power.device-idle.performance':
    "$q=powercfg /query SCHEME_CURRENT SUB_NONE 4faab71a-92e5-4726-b531-224559672d19 | Out-String; if($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($q)){Write-Output 'UNKNOWN: Windows did not return the device-idle power setting.'; exit 2}; if([regex]::Matches($q,'0x00000000').Count -ge 2){exit 0}; Write-Output 'MISMATCH: Device idle performance is not set to maximum for both AC and DC.'; exit 1",
  'power.pcie.link-state.off':
    powerSettingVerifier(PCI_EXPRESS_SUBGROUP, PCI_EXPRESS_LINK_STATE, 'PCIe Link State Power Management'),
  'power.usb3.link-power.disable':
    powerSettingVerifier(USB_SUBGROUP, USB_LINK_POWER, 'USB link power management'),
  'process.msi-mode.gpu-nic-audio':
    "$found=0; $bad=0; $unreadable=0; foreach($c in @('Display','Net','AudioEndpoint')){try{$devices=Get-PnpDevice -Class $c -PresentOnly -ErrorAction Stop | Where-Object {$_.Status -eq 'OK' -and $_.InstanceId -like 'PCI\\*'}}catch{$unreadable++; continue}; foreach($d in $devices){$found++; $p=\"HKLM:\\SYSTEM\\CurrentControlSet\\Enum\\$($d.InstanceId)\\Device Parameters\\Interrupt Management\\MessageSignaledInterruptProperties\"; try{$v=(Get-ItemProperty -Path $p -Name MSISupported -ErrorAction Stop).MSISupported; if([int]$v -ne 1){$bad++}}catch{$unreadable++}}}; if($found -eq 0 -or $unreadable -gt 0){Write-Output 'UNKNOWN: Windows could not read MSI support for every present PCI display, network, or audio endpoint.'; exit 2}; if($bad -gt 0){Write-Output ('MISMATCH: '+$bad+' present PCI device(s) do not have MSI enabled.'); exit 1}; exit 0",
  'net.nic.rsc.disable':
    `${ACTIVE_PHYSICAL_ROUTE}$r=Get-NetAdapterRsc -Name $a.Name -ErrorAction SilentlyContinue; if(-not $r){Write-Output 'NOT_APPLICABLE: RSC is not exposed by the active adapter.'; exit 2}; if($r.IPv4Enabled -or $r.IPv6Enabled){Write-Output 'MISMATCH: Receive Segment Coalescing is still enabled on the active adapter.'; exit 1}; exit 0`,
  'net.nic.lso.disable':
    `${ACTIVE_PHYSICAL_ROUTE}$r=Get-NetAdapterLso -Name $a.Name -ErrorAction SilentlyContinue; if(-not $r){Write-Output 'NOT_APPLICABLE: LSO is not exposed by the active adapter.'; exit 2}; if($r.IPv4Enabled -or $r.IPv6Enabled){Write-Output 'MISMATCH: Large Send Offload is still enabled on the active adapter.'; exit 1}; exit 0`,
  'net.nic.eee-powersave.disable':
    `${ACTIVE_PHYSICAL_ROUTE}$names=@('Energy Efficient Ethernet','Energy-Efficient Ethernet','Green Ethernet','EEE','Advanced EEE','Power Saving Mode','Gigabit Lite','Ultra Low Power Mode'); $targets=@(); foreach($dn in $names){$p=Get-NetAdapterAdvancedProperty -Name $a.Name -DisplayName $dn -ErrorAction SilentlyContinue; if($p){$targets+=([pscustomobject]@{ kind='advanced'; displayName=$dn })}}; $pm=Get-NetAdapterPowerManagement -Name $a.Name -ErrorAction SilentlyContinue; if($pm -and $pm.PSObject.Properties.Name -contains 'AllowComputerToTurnOffDevice' -and [string]$pm.AllowComputerToTurnOffDevice -in @('Enabled','Disabled')){$targets+=([pscustomobject]@{ kind='power'; displayName='AllowComputerToTurnOffDevice' })}; if($targets.Count -eq 0){Write-Output 'NOT_APPLICABLE: The active adapter exposes no supported NIC power-saving properties.'; exit 2}; $f=Join-Path $env:LOCALAPPDATA 'optmaxxing\\backups\\nic-eee-stash.json'; if(-not (Test-Path -LiteralPath $f)){Write-Output 'NOT_CONFIGURED: NIC power-saving restore state is absent; first apply will capture the active adapter state.'; exit 2}; try{$state=Get-Content -LiteralPath $f -Raw | ConvertFrom-Json}catch{Write-Output 'UNKNOWN: NIC power ownership record cannot be read; use Settings -> Restore/repair before retrying.'; exit 2}; if([int]$state.schema -ne 2 -or [string]$state.owner -ne 'optimizationmaxxing' -or [string]$state.identity -ne $identity -or [int]$state.interfaceIndex -ne $idx){Write-Output 'UNKNOWN: NIC power ownership record does not match the active adapter; use Settings -> Restore/repair before retrying.'; exit 2}; $ownedTargets=@($state.targets); if($ownedTargets.Count -eq 0){Write-Output 'UNKNOWN: NIC power ownership record contains no restorable properties; use Settings -> Restore/repair before retrying.'; exit 2}; foreach($t in $ownedTargets){if([string]$t.kind -eq 'advanced'){$p=Get-NetAdapterAdvancedProperty -Name $a.Name -DisplayName ([string]$t.displayName) -ErrorAction SilentlyContinue; if(-not $p -or $p.DisplayValue -notmatch '^(Disabled|Off|No)$'){Write-Output ('MISMATCH: '+$t.displayName+' is not disabled on the active adapter.'); exit 1}}elseif([string]$t.kind -eq 'power'){$pm=Get-NetAdapterPowerManagement -Name $a.Name -ErrorAction SilentlyContinue; if(-not $pm -or $pm.AllowComputerToTurnOffDevice.ToString() -notmatch '^(Disabled|Off|No|False)$'){Write-Output 'MISMATCH: NIC power-down is not disabled on the active adapter.'; exit 1}}}; exit 0`,
  'peripherals.rgb-control-apps.autostart-disable':
    "$kw=@('aura','icue','mystic light','synapse','g-hub','ghub','t-force','nzxt cam','steelseries gg','polychrome'); $runKeys=@('HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run','HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run','HKLM:\\Software\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Run'); foreach($p in $runKeys){if(Test-Path $p){$props=Get-ItemProperty -Path $p; foreach($n in $props.PSObject.Properties.Name){if($n -like 'PS*'){continue}; $hay=\"$n $($props.$n)\"; foreach($k in $kw){if($hay -like \"*$k*\"){Write-Output ('MISMATCH: RGB control autostart remains enabled ('+$hay+').'); exit 1}}}}}; try{foreach($t in Get-ScheduledTask -ErrorAction Stop){if([string]$t.State -eq 'Disabled'){continue}; $hay=\"$($t.TaskName) $($t.TaskPath)\"; foreach($k in $kw){if($hay -like \"*$k*\"){Write-Output ('MISMATCH: RGB control scheduled task remains enabled ('+$hay+').'); exit 1}}}}catch{}; exit 0",
}
